# Generated by Django 5.1.15 on 2026-10-08 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Capa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_what', models.TextField(verbose_name='问题描述')),
                ('root_cause_why', models.TextField(blank=True, verbose_name='根因分析')),
                ('action_who', models.CharField(blank=True, max_length=100, verbose_name='负责人')),
                ('target_date_when', models.DateField(blank=True, null=True, verbose_name='目标完成日期')),
                ('location_where', models.CharField(blank=True, max_length=200, verbose_name='实施位置')),
                ('method_how', models.TextField(blank=True, verbose_name='实施办法')),
                ('cost_howmuch', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='预算')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('pending', '待审'), ('effective', '生效'), ('closed', '关闭')], default='draft', max_length=20)),
                ('effectiveness_score', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'CAPA 措施',
                'verbose_name_plural': 'CAPA 措施',
            },
        ),
        migrations.CreateModel(
            name='DefectType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': '缺陷类型',
                'verbose_name_plural': '缺陷类型',
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('uscc_code', models.CharField(max_length=20, unique=True, verbose_name='统一社会信用代码')),
                ('address', models.TextField(blank=True)),
                ('contact_phone', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '生产者',
                'verbose_name_plural': '生产者',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='system', max_length=100)),
                ('action', models.CharField(choices=[('create', '创建'), ('update', '更新'), ('delete', '删除')], max_length=10)),
                ('target_model', models.CharField(max_length=50)),
                ('target_id', models.IntegerField()),
                ('before_json', models.JSONField(blank=True, null=True)),
                ('after_json', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '审计日志',
                'verbose_name_plural': '审计日志',
                'indexes': [models.Index(fields=['target_model', 'target_id'], name='qms_app_aud_target__f30f17_idx')],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='qms_app.manufacturer')),
            ],
            options={
                'verbose_name': '产品',
                'verbose_name_plural': '产品',
            },
        ),
        migrations.CreateModel(
            name='Recall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recall_id_external', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='外部公告编号')),
                ('source_type', models.CharField(choices=[('samrdprc_gg', 'samrdprc 公告'), ('samrdprc_news', 'samrdprc 新闻'), ('samr_zhdt', 'samr 主站')], max_length=20)),
                ('source_url', models.TextField()),
                ('raw_html_path', models.CharField(blank=True, max_length=500)),
                ('recall_date', models.DateField()),
                ('quantity', models.IntegerField(default=0)),
                ('defect_description', models.TextField()),
                ('consequence', models.TextField()),
                ('remedy_method', models.TextField()),
                ('status', models.CharField(choices=[('active', '执行中'), ('completed', '已完成'), ('cancelled', '已撤销')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('defect_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='qms_app.defecttype')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recalls', to='qms_app.product')),
            ],
            options={
                'verbose_name': '召回事件',
                'verbose_name_plural': '召回事件',
            },
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('severity_predicted', models.CharField(blank=True, choices=[('high', '高'), ('medium', '中'), ('low', '低')], max_length=10)),
                ('severity_confidence', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('capa_draft', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_complaint', to='qms_app.capa')),
                ('similar_recall', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='qms_app.recall')),
            ],
            options={
                'verbose_name': '客户投诉',
                'verbose_name_plural': '客户投诉',
            },
        ),
        migrations.AddField(
            model_name='capa',
            name='recall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capas', to='qms_app.recall'),
        ),
        migrations.AddIndex(
            model_name='recall',
            index=models.Index(fields=['source_type', 'recall_date'], name='qms_app_rec_source__9e0473_idx'),
        ),
    ]
