# Generated by Django 5.1.15 on 2026-10-08 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qms_app', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='recall',
            constraint=models.CheckConstraint(condition=models.Q(('source_type__in', ['samrdprc_gg', 'samrdprc_news', 'samr_zhdt'])), name='recall_source_type_valid'),
        ),
    ]
