# Generated by Django 5.1.15 on 2026-10-09 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qms_app', '0002_recall_recall_source_type_valid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='target_id',
            field=models.BigIntegerField(),
        ),
    ]
